### ISSUE TITLE
Db2 Modules 

### ISSUE THREAD

**Issue by jabrooks** [ibmdb/vscode-extension#26]
PLease implement working with Modules.  I am working on an app with 100+ routines and we are organizing them with Modules.  Data Studio only partially supports Modules.  Please support organizing   functions and procedure by schema/by module.  Please support debugging routines in Modules.

Otherwise, I'm excited to see this product.  Thanks.

Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by akhilravuri1** [comment]
Hi @jabrooks 

With the current version functions and procedures are organized by the schema. You can see the list of functions or procedures under the schema.

![image](https://user-images.githubusercontent.com/32290825/106557007-e0e2ad00-6546-11eb-8799-5c006029d63b.png)

Please let me know if you need any help.

Thanks,
Akhil

**Comment by jabrooks** [comment]
Yes, you can see functions and procs.  However, There is another level of organization Db2 uses - Modules.  Examples are SYSIBMADM.DBMS_ALERT.CHECK_ALERT_NAME().  The format is SCHEMA.MODULE.PROCEDURE().  This is a three-tier name compared to your example NEWTON.MYPROC(), which is only two tiers - SCHEMA.PROCEDURE().  

https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.sqlpl.doc/doc/c0053741.html

As my team is developing SQL PL applications, the third level of organization helps a great deal, but we do struggle finding tools, including IBM tools (Poke at ATS and DataStudio ) that fully support Modules.  

This extension is a relatively new tool, it would be nice to have full support for Modules.  I would switch from DBeaver and Data Studio for development with this feature.

snipped from Data Studio Data Source Explorer:
![Screenshot of module](https://user-images.githubusercontent.com/11554055/106602093-84719480-652a-11eb-9de2-206a742c1692.png)

**Comment by akhilravuri1** [comment]
Hi @jabrooks 

I will install data studio and explore this.
Thanks for the input.

-Akhil

**Comment by TilenRupar** [comment]
The VS code extension stopped building Native Modules. 

Vs code error:
Failed to rebuild native modules, please reach out to our git page for help

I can install the extension, but none of the functionalities work:
command 'extension.Db2Connect' not found

Anybody else having this issue?

**Comment by bimalkjha** [comment]
@TilenRupar Use `View -> Command Palette -> Db2: Rebuild Native Modules` option and rebuild the module. It should fix the problem. Thanks.

**Comment by TilenRupar** [comment]
Ive tried it but it does not fix the issue.
Thank you for your quick reply.

**Comment by bimalkjha** [comment]
@TilenRupar Please open a new issue with details like OS name and architecture.. this issue is for different problem. Thanks.

**Comment by bimalkjha** [comment]
@jabrooks Delivered code changes for module support and it will available with next release of db2connect extension.
For testing purpose, you can download https://github.com/ibmdb/vscode-extension/blob/master/db2connect-2.3.1.vsix and `install from VSIX` file.
Latest released version of db2connect extension is v2.3.1 on Marketplace which do not has this feature yet. It will be available in next release. Thanks.
